function p = sopi_problem()
    p = mlist(['sopiPro',...
               'vars',...
               'varsId',...
               'varsIdx',...
               'nvar',...
               'lb',...
               'ub',...
               'A',...
               'b',...
               'Ae',...
               'be'])
    p.vars = list()
    p.varsId = []
    p.varsIdx = list()
    p.nvar = 0
    p.lb = []
    p.ub = []
    p.A = []
    p.b = []
    p.Ae = []
    p.be = []
endfunction
